import { Platform, StyleSheet } from "react-native";
import { AppColors } from "@/constants/theme";

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    padding: 16,
    backgroundColor: colors.background,
    paddingBottom: Platform.OS === 'android' ? 100 : 40,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: colors.text,
  },
  subtitle: {
    color: colors.textSecondary,
    marginTop: 4,
  },
  label: {
    fontSize: 16,
    fontWeight: "500",
    marginBottom: 8,
    marginTop: 16,
    color: colors.icon,
  },
  input: {
    backgroundColor: colors.inputBg,
    borderRadius: 16,
    padding: 14,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
  },
  amountInput: {
    backgroundColor: colors.inputBg,
    borderRadius: 16,
    padding: 18,
    fontSize: 22,
    fontWeight: "600",
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 8,
  },
  categoryCard: {
    width: "30%",
    backgroundColor: colors.surfaceSecondary,
    borderRadius: 16,
    paddingVertical: 20,
    alignItems: "center",
    marginBottom: 12,
  },
  categorySelected: {
    backgroundColor: colors.primaryLight,
    borderWidth: 2,
    borderColor: colors.primary,
  },
  categoryIcon: {
    fontSize: 28,
    marginBottom: 8,
  },
  categoryLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: colors.text,
  },
  categoryLabelSelected: {
    fontWeight: "700",
  },
  notesInput: {
    backgroundColor: colors.inputBg,
    borderRadius: 16,
    padding: 14,
    fontSize: 16,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 80,
    textAlignVertical: "top",
    color: colors.text,
  },
  saveButton: {
    marginTop: 24,
    backgroundColor: colors.primary,
    borderRadius: 18,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  templateSection: {
    marginBottom: 8,
  },
  templateLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textSecondary,
    marginBottom: 8,
    marginTop: 8,
  },
  templateChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginRight: 10,
    borderWidth: 1,
    borderColor: colors.border,
    minWidth: 120,
  },
  templateChipIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  templateChipText: {
    flexShrink: 1,
  },
  templateChipTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.text,
    maxWidth: 100,
  },
  templateChipAmount: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
    marginTop: 1,
  },
  templateToggle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    marginTop: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  templateToggleLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  templateToggleText: {
    fontSize: 15,
    color: colors.icon,
    fontWeight: "500",
    marginLeft: 8,
  },
  tagContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  tagChip: {
    borderWidth: 1.5,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: colors.surface,
  },
  tagChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.icon,
  },
  tagAddButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primaryLight,
    justifyContent: "center",
    alignItems: "center",
  },
  newTagRow: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  newTagInput: {
    backgroundColor: colors.surfaceSecondary,
    borderRadius: 10,
    padding: 10,
    fontSize: 14,
    marginBottom: 8,
    color: colors.text,
  },
  tagColorRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  tagColorDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  tagColorDotSelected: {
    borderWidth: 3,
    borderColor: colors.text,
  },
  tagCreateButton: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: "center",
  },
  tagCreateText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 14,
  },
  paymentMethodRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  paymentMethodButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: colors.surfaceSecondary,
    borderRadius: 16,
    paddingVertical: 14,
    borderWidth: 2,
    borderColor: "transparent",
  },
  paymentMethodSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  paymentMethodText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
  },
  paymentMethodTextSelected: {
    color: "#fff",
  },
});
