import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    padding: 16,
    backgroundColor: "#f6f7f9",
    paddingBottom: 32,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
  },
  subtitle: {
    color: "#6b7280",
    marginTop: 4,
  },
  label: {
    fontSize: 16,
    fontWeight: "500",
    marginBottom: 8,
    marginTop: 16,
    color: "#374151",
  },
  input: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  amountInput: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 18,
    fontSize: 22,
    fontWeight: "600",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 8,
  },
  categoryCard: {
    width: "30%",
    backgroundColor: "#f3f4f6",
    borderRadius: 16,
    paddingVertical: 20,
    alignItems: "center",
    marginBottom: 12,
  },
  categorySelected: {
    backgroundColor: "#dcfce7",
    borderWidth: 2,
    borderColor: "#22c55e",
  },
  categoryIcon: {
    fontSize: 28,
    marginBottom: 8,
  },
  categoryLabel: {
    fontSize: 14,
    fontWeight: "500",
    color: "#111827",
  },
  categoryLabelSelected: {
    fontWeight: "700",
  },
  notesInput: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    minHeight: 80,
    textAlignVertical: "top",
  },
  saveButton: {
    marginTop: 24,
    backgroundColor: "#22c55e",
    borderRadius: 18,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  templateSection: {
    marginBottom: 8,
  },
  templateLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6b7280",
    marginBottom: 8,
    marginTop: 8,
  },
  templateChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    minWidth: 120,
  },
  templateChipIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  templateChipText: {
    flexShrink: 1,
  },
  templateChipTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#222",
    maxWidth: 100,
  },
  templateChipAmount: {
    fontSize: 12,
    color: "#22c55e",
    fontWeight: "600",
    marginTop: 1,
  },
  templateToggle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  templateToggleLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  templateToggleText: {
    fontSize: 15,
    color: "#374151",
    fontWeight: "500",
    marginLeft: 8,
  },
  tagContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  tagChip: {
    borderWidth: 1.5,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: "#fff",
  },
  tagChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
  },
  tagAddButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#dcfce7",
    justifyContent: "center",
    alignItems: "center",
  },
  newTagRow: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  newTagInput: {
    backgroundColor: "#f3f4f6",
    borderRadius: 10,
    padding: 10,
    fontSize: 14,
    marginBottom: 8,
  },
  tagColorRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 8,
  },
  tagColorDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  tagColorDotSelected: {
    borderWidth: 3,
    borderColor: "#222",
  },
  tagCreateButton: {
    backgroundColor: "#22c55e",
    borderRadius: 10,
    paddingVertical: 8,
    alignItems: "center",
  },
  tagCreateText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 14,
  },
  adArea: {
    marginTop: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
    alignItems: "center",
  },
  adText: {
    color: "#9ca3af",
    fontWeight: "600",
  },
});
